#!/bin/csh 

# creates sac macro moreppk for ppk calls 

if($#argv<3) then
  echo Usage: mkmoreppk head tail file
  echo e.g. mkmoreppk -6 +8 G.CAN*SAC
  echo windows ppk to t0-6 and t0+8
  exit
endif  

echo 'oapf name' > moreppk
echo 'fileid type list kstnm gcarc' >> moreppk
echo 'fileid location UL' >> moreppk

# picks
echo window 1 xsize 0.01 0.5 ysize 0.2 0.96 >> moreppk

echo r $argv[3] >> moreppk
echo xlim t0 $argv[1] t0 $argv[2] >> moreppk
echo hp co 1 >> moreppk
echo r more $argv[3] >> moreppk
echo ch ka A >> moreppk
echo ppk perplot 2 >> moreppk
echo wh >> moreppk

echo capf >> moreppk
echo quit >> moreppk

/usr/local/sac/bin/sac moreppk
