#! /bin/csh
if(-e avoid) then
  echo start cleaning rundopicks of small events
else
  echo the file named avoid is missing
  exit
endif  
set a = `wc rundopicks`
cp rundopicks rundopicks.original
echo for extra safety rundopicks.original is copy of current rundopicks
sed -f avoid rundopicks > rundopicks.cleaned
echo rundopicks has been cleaned of small events
set b = `wc rundopicks.cleaned`
echo number of Qnn directories in the original is $a[1]
echo after cleaning it is $b[1]
echo if something went wrong you should still have your unchanged rundopicks
echo ' '
echo to work with the clean version do: mv rundopicks.cleaned rundopicks
