#! /bin/csh

set mybase = `pwd`
if(! -e ADDTOS) then   # create directory for add_to files
  mkdir ADDTOS
  chmod a+w ADDTOS
  echo Directory ADDTOS was created in $mybase
endif  
echo ' '
echo '------------------------------------------------------------'  
echo Running PPK on             $argv[1]

cd $argv[1]
if(-e APF) then
  set a = `ls add_to_datafile.*[0-9] | wc`
  if($a[1]>0) then
    mv add_to_datafile.*[0-9] add_to_datafile.old
    echo Existing add_to file was saved in add_to_datafile.old
    echo picks are added to APF, new add_to file will also have old picks
  endif
endif  
cat quake
gv smap.pdf &
pause
gv pmap.pdf &
pause
gv sisaz.pdf &
pause
gv pplt1.pdf &
pause
if(-e pplt2.pdf) then
  gv pplt2.pdf &
  pause
endif  
if(-e pplt3.pdf) then
  gv pplt3.pdf &
  pause
endif  
if(-e stf.pdf) then
  gv stf.pdf &
  endif
endif  

mkdoppk
/usr/local/sac/bin/sac doppk

echo 'end of:'
pwd
echo '----------------------------------------------------------------'
echo -n '[n]ext event, re[j]ect this event, give nonzero [t]bias, or [r]epeat? '
set ans = $<:q
if ($ans == 'n') then
  rdapf2 P 0.4 
  vi add_to_datafile*[0-9]
  pointa
  pltres add_to_datafile*[0-9]
  cp add_to_datafile*[0-9] ${mybase}/ADDTOS
  exit
else if($ans == 'j') then
  rm -f add_to_datafile*[0-9]
  rm -f APF*
  exit
else if($ans == 't') then
  echo -n 'Give tbias for rdapf2: '
  set tbias = $<:q
  rdapf2 P 0.4 $tbias
  vi add_to_datafile*
  pointa
  pltres add_to_datafile*[0-9]
  cp add_to_datafile*[0-9] ${mybase}/ADDTOS
  exit
else if($ans == 'r') then
  echo -n 'Give tbias for rdapf2, or 0: '
  set tbias = $<:q
  rdapf2 P 0.4 $tbias
  pointa
  rm add_to*[0-9]
  /usr/local/sac/bin/sac doppk
  rdapf2 P 0.4 $tbias
  vi add_to_datafile*[0-9]
  pointa
  pltres add_to_datafile*[0-9]
  cp add_to_datafile*[0-9] ${mybase}/ADDTOS
  echo 'end of:'
  pwd
  echo '----------------------------------------------------------------'
else  
  echo -n 'You must answer either n,t or r, so please try again:'
  set ans = $<:q
  echo your answer is $ans
  if($ans == 't') then
    echo -n 'Give tbias for rdapf2: '
    set tbias = $<:q
    rdapf2 P 0.4 $tbias
    vi add_to_datafile*[0-9]
    pointa
    pltres add_to_datafile*[0-9]
    cp add_to_datafile*[0-9] ${mybase}/ADDTOS
    exit
  else if($ans == 'j') then
    rm -f add_to_datafile*[0-9]
    rm -f APF*
    exit
  else if($ans == 'r') then
    echo -n 'Give tbias for rdapf2, or 0: '
    set tbias = $<:q
    rm add_to*
    /usr/local/sac/bin/sac doppk
    rdapf2 P 0.4 $tbias
    vi add_to_datafile*[0-9]
    pointa
    pltres add_to_datafile*[0-9]
    cp add_to_datafile*[0-9] ${mybase}/ADDTOS
    echo 'end of:'
    pwd
    echo '----------------------------------------------------------------'
    exit
  else
    echo 'I assume you meant <n>ext'
    rdapf2 P 0.4 
    vi add_to_datafile*[0-9]
    pointa
    pltres add_to_datafile*[0-9]
    cp add_to_datafile*[0-9] ${mybase}/ADDTOS
  endif  
endif  
